In [2]:
pwd


'C:\\Users\\ssamarthi\\AnacondaProjects\\SAHIL_TUTORIALS\\vehicle reservation'

In [21]:
VEHICLE_TYPES = ('Car', 'Van', 'Truck')
VEHICLES_FILENAME = 'VehiclesStock.txt'
VEHICLE_COSTS_FILENAME = 'RentalCost.txt'
class suman:
    def __init__(self):
        """Populates vehicles and rental costs from file. Raises IOError."""
        
        self.__vehicles = Vehicles()
        self.__vehicle_costs = VehicleCosts()
        self.__reservations = Reservations()
        self.__vehicle_info_file = None
    try:
        self.__vehicle_info_file = open(VEHICLES_FILENAME, 'r')
        self.__rental_cost_file = open(VEHICLE_COSTS_FILENAME, 'r')         
    except Exception as e:
        print(e)   

name 'self' is not defined


In [4]:
rentalAgencyProgram.py

NameError: name 'rentalAgencyProgram' is not defined

In [26]:
with open('duyfile.txt','w') as f:
    for i in list(range(10)):
        f.write('abcd')
        f.write('\n')

In [36]:
with open('duyfile.txt', 'r') as fh:
    tmp = fh.readline()
    print(tmp)

1.abcd



In [41]:
#bubble sort algorithm
from array import *

arry1 = array('i',[])
num = int(input('Enter number of elements:'))

for i in list(range(num)):
    elm = input('Enter element')
    arry1.append(int(elm))
print (arry1)    

flag = False
for i in list(range(num-1)):
    for j in list(range(num-1-i)):
        if (arry1[j] > arry1[j+1]):
            t = arry1[j]
            arry1[j] = arry1[j+1]
            arry1[j+1] = t
            flag = True
    if flag == False:
        print ('Already Sorted')
        break
    else:
        flag = True
print ('Sorted array:',arry1)        
        
            

Enter number of elements:3
Enter element10
Enter element20
Enter element30
array('i', [10, 20, 30])
Already Sorted
Sorted array: array('i', [10, 20, 30])


In [45]:
#Buble sort algorithm
from array import *
ary = array('i',[])

n = int(input('Enter number of elements'))
for i in list(range(n)):
    elm = input('Enter element:')
    ary.append(int(elm))
print(ary)

flag = False
for i in range(n-1):
    for j in range(n-1-i):
        if ary[j] > ary[j+1]:
            t = ary[j]
            ary[j] = ary[j+1]
            ary[j+1] = t
            flag = True
    if flag == False:
        print('Already sorted array:',ary)
    else:
        flag = False
print('Sorted array:',ary)        

Enter number of elements3
Enter element:40
Enter element:60
Enter element:10
array('i', [40, 60, 10])
Sorted array: array('i', [10, 40, 60])


In [46]:
from numpy import *
m = matrix([[1,2,3],[4,5,6]])
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [47]:
m1 = matrix('1,2,3;4,5,6')
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [48]:
m2 = matrix(arange(12).reshape(4,3))
m2

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [49]:
m3 = reshape(matrix(arange(12)),(4,3))
m3

matrix([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [54]:
#marks percentage

marks = input('Enter marks space seperated').split(' ')
print (marks)

sum = 0
for i in range(len(marks)):
    sum += int(marks[i])
print (sum)
percentage = sum/len(marks)
print('Percentage:',percentage)

Enter marks space seperated10 20 30
['10', '20', '30']
60
Percentage: 20.0


In [56]:
dct = {'suman':5000,'sanvith':100000,'archana':80000}
dct

{'archana': 80000, 'sanvith': 100000, 'suman': 5000}

In [64]:
for k,v in dct.items():
    print('Name={:15s} amount={:10.2f}'.format(k,v))

Name=suman           amount=   5000.00
Name=sanvith         amount= 100000.00
Name=archana         amount=  80000.00


In [66]:
dct.items()

dict_items([('suman', 5000), ('sanvith', 100000), ('archana', 80000)])

In [76]:
class my_exception(Exception):
    def __init__(self,msg):
        self.arg = msg
    def check(dcct):
        for k,v in dcct.items():
            print ('Name={:15s} Balance={:10.2f}'.format(k,v))
            if (v < 2000.00):
                raise my_exception ('Balance is less then 2K')
            else:
                pass
    dcct = {'suman':2500,'sanvith':1500}
    try:
        check(dcct)
    except Exception as me:
        print (me)             
            

Name=suman           Balance=   2500.00
Name=sanvith         Balance=   1500.00
Balance is less then 2K


In [89]:
def kwargs(**args):
    print ('H8i:',args)
    args = list(args[0])
    print ('H8i:',args)
    for i in args:
        i += 1
        print(i)
kwargs({'a':1,'b':2})        

TypeError: kwargs() takes 0 positional arguments but 1 was given

In [84]:
lst = [1,2,3,6]
for i in lst:
    i += 1
    print (i)

2
3
4
7


In [117]:
def kwargs(*args):
    type(args)
kwargs([1,2,3,4])        

In [94]:
tup = (1,2,3,4)
for i in tup:
    i += 1
    print (i)

2
3
4
5


In [95]:
type(tup)

tuple

In [113]:
tup.count(1)

1

In [151]:
def hello(**kwargs):
    if kwargs is not None:
        for k,v in kwargs.items():
            print ('%s == %s'%(k,v))

In [152]:
#dct = {"name" : "suman"}
kwargs(name="suman")

AttributeError: 'dict' object has no attribute 'iteritems'

In [145]:
dct={'a':1,'b':2}

In [147]:
dct.items()

dict_items([('a', 1), ('b', 2)])

In [159]:
def trying(**kwargsa):
    if kwargsa is not None:
        for k,v in kwargsa:
            print('%s == %s'%(k,v))

In [160]:
trying(name="suman")

ValueError: too many values to unpack (expected 2)

In [158]:
print ('suman')

suman


In [161]:
def testify(arg1,arg2,arg3):
    print ('ARG1',arg1)
    print ('ARG2',arg2)
    print ('ARG3',arg3)

In [162]:
kwargs = ('hey','Hello','Babu')
testify(*kwargs)

ARG1 hey
ARG2 Hello
ARG3 Babu


In [168]:
#kwargs = {'1':'hey','2':'Hello','3':'Babu'}
kwargs = {"arg1" : "hey", "arg2" : 14, "arg3" : "joey"}
testify(**kwargs)

ARG1 hey
ARG2 14
ARG3 joey
