In [44]:
# Arrays - similar list but in this you can only store one type data. 
# numpy

In [ ]:
type code    size

'b' - signed integer - 1 
'B' - unsigned integer - 1
'i' - signed integer - 2 
'I' - unsigned integer - 2
'l' - signed integer - 4
'L' - unsigned integer - 4
'f' - floating point - 4
'd' - double precision floating point - 8
'u' - unicode character  - 2

In [2]:
# arrayname = array(type code,[elements])

In [ ]:
tuple1 = (1,2,3,4)
arrayname = array('i',[1,2,3,4])

In [46]:
list = [1,'a',20,'hi']

In [5]:
from array import * # array package 
a = array('i',[4,6,2,9]) # type of integer array

In [6]:
a

array('i', [4, 6, 2, 9])

In [13]:
# float type array, f , d = double precision floating point

arr = array('d',[1.5,-2.2,3,5.75])

In [8]:
arr

array('d', [1.5, -2.2, 3.0, 5.75])

In [9]:
# printing an array

In [45]:
for el in a:
    print (el)

4
6
2
9


In [12]:
for element in arr:
    print (element)

1.5
-2.2
3.0
5.75


In [14]:
# character array

from array import *
arr = array('u',['a','b','c','d','e'])

print ('The array element are : ')
for ch in arr:
    print (ch)

The array element are : 
a
b
c
d
e


In [25]:
# creating array from another array
from array import *

arr3 = array('d',[1.5,2.5,-3.5,4])

arr4 = array(arr3.typecode,(a*3 for a in arr3))

for i in arr4:
    print (i)

4.5
7.5
-10.5
12.0


In [26]:
# Indexing and Slicing on Arrays

In [ ]:
10 20 30 40 50
0   1  2  3  4

In [27]:
# ex 

from array import *
x = array('i', [10,20,30,40,50]) # type integer

n = len(x)

for i in range(n):
    print (x[i], end=' ')

10 20 30 40 50 

In [28]:
# 

from array import *
x = array('i', [10,20,30,40,50])

n = len(x)

i = 0
while i < n:
    print (x[i], end = ' ')
    i += 1


10 20 30 40 50 

In [30]:
y = x[1:4]
print (y)

y = x[0:]
print (y)

y = x[:4]
print (y)

array('i', [20, 30, 40])
array('i', [10, 20, 30, 40, 50])
array('i', [10, 20, 30, 40])


In [32]:
# ex 

from array import *
x = array('i',[10,20,30,40,50,60,70])

for i in x[2:5]: # slicing a portion of the array 
    print (i)

30
40
50


In [33]:
# processing the arrays 

In [36]:
# ex

from array import *

arr = array('i',[10,20,30,40,50])
print ('orig array: ', arr)

arr.append(60)
arr.append(70)

print ('modified array: ', arr)

arr.insert(1,99)
print ('modified array: ', arr)

arr.remove(20)
print ('modified array: ', arr)

n = arr.pop()
print ('modified array: ', arr)

# convert an array into a list using tolist()
lst = arr.tolist()
print ('List: ', lst)
print ('Array: ', arr)


orig array:  array('i', [10, 20, 30, 40, 50])
modified array:  array('i', [10, 20, 30, 40, 50, 60, 70])
modified array:  array('i', [10, 99, 20, 30, 40, 50, 60, 70])
modified array:  array('i', [10, 99, 30, 40, 50, 60, 70])
modified array:  array('i', [10, 99, 30, 40, 50, 60])
List:  [10, 99, 30, 40, 50, 60]
Array:  array('i', [10, 99, 30, 40, 50, 60])


In [50]:
# ex 

#from array import *
str = input('Enter marks: ').split(' ')

marks = [ int(num) for num in str] 
type(marks)

sum = 0 
for x in marks:
    print (x)
    sum += x
print ('Total marks: ', sum)

n = len(marks)
percent = sum/n
print ('Percentage: ', percent)

Enter marks: 10 20 30
10
20
30
Total marks:  60
Percentage:  20.0


In [52]:
# sorting an array using Bubble sort technique

x = array('i',[]) # empty list

print ('How many elements: ', end='')
n = int(input()) # getting a user input

for i in range(n): # how many elements
    print ('Enter element: ', end='')
    x.append(int(input())) # populating array
    
print ('Original array: ', x)

# bubble sorting 
flag = False # when the swapping is done, flag becomes True
for i in range(n-1): # i is from 0 to n-1
    for j in range(n-1-i): # j is from 0 to one element lesser than i
        if x[j] > x[j+1]: # if 1st element is bigger than the 2nd one
            t = x[j] # swap j and j+1 elements
            x[j] = x[j+1]
            x[j+1] = t
            flag = True # swapping done, hence flag is True. 
    if flag == False: # no swapping is done, array is in sorted order
            break # come out of loop. 
    else:
        flag = False # assing initial value to flag. 
print ('Sorted array= ', x)


How many elements: 5
Enter element: 20
Enter element: 10
Enter element: 50
Enter element: 30
Enter element: 40
Original array:  array('i', [20, 10, 50, 30, 40])
Sorted array=  array('i', [10, 20, 30, 40, 50])


In [56]:
# ex
from array import *

x = array('i', [])

print ('How many elements? ', end='')
n = int(input()) 

for i in range(n):
    print ('Enter element: ', end='')
    #x.append(int(input())) # add the element to the array x 
    x.append(int(input()))
    
print ('Original array: ', x)

s = int(input()) # searching an element

flag = False

for i in range(len(x)):
    if s == x[i]:
        print ('Found at Position= ', i+1)
        flag = True
    if flag == False:
        print ('Not found in the array')

How many elements? 5
Enter element: 20
Enter element: 40
Enter element: 20
Enter element: 55
Enter element: 10
Original array:  array('i', [20, 40, 20, 55, 10])
20
Found at Position=  1
Found at Position=  3


In [ ]:
# Types of Arrays

- Single Dimensional arrays
- Multi-Dimensional array 

In [2]:
from array import *
marks = array('i',[50,60,70,80])

In [4]:
marks = array([[50,60,70,80], # first student
             [40,70,70,80], # second student
             [30,60,70,80]]) # third student

TypeError: array() argument 1 must be a unicode character, not list

In [59]:
# numpy 

In [60]:
import numpy
arr = numpy.array([10,20,30,40,50])
print (arr)

[10 20 30 40 50]


In [61]:
import numpy as np
arr = np.array([10,20,30,40,50])
print (arr)

[10 20 30 40 50]


In [62]:
# functions
# array()
# linspace()
# logspace()
# arange()
# zeros() and ones() functions

In [63]:
# Creating arrays using array()

In [67]:
from numpy import * # import the package
arr = array(['a','b','c','d','e'])
print (arr)

['a' 'b' 'c' 'd' 'e']


In [69]:
from numpy import *
arr = array(['Delhi','Indore'],dtype=str)
print (arr)

TypeError: data type not understood

In [70]:
# ex copy array

from numpy import *
a = array([1,2,3,4,5])

b = array(a) # creating b from a using array() function

c = a

print (a)
print (b)
print (c)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [72]:
# creating arrays linspace

In [73]:
# a = linspace(0,10,5)

In [105]:
from numpy import *

a = linspace(0,10,5) # drivide 0 to 10 into 5 parts
print (a)

[  0.    2.5   5.    7.5  10. ]


In [75]:
# logspace - similart to linspace

# logspace(start,stop,n)

In [77]:
from numpy import *

a = logspace(1,5,5) # divide 1 power 10 to 4 power 10 into 5 equal parts

n = len(a)

for i in range(n):
    print ('%.1f' % a[i], end=' ')

10.0 100.0 1000.0 10000.0 100000.0 

In [81]:
# ex 

from numpy import *
a = arange(2,11,2) # arange(start,stop,stepsize)
print (a)

[ 2  4  6  8 10]


In [82]:
# creating arrays using zeros() and ones() function

In [83]:
# zeroes(n,datatype)
# ones(n,datatype)

In [107]:
from numpy import *
a = zeros(6,int)
print (a)

b = ones(7,int)
print (b)

[0 0 0 0 0 0]
[1 1 1 1 1 1 1]


In [86]:
# Mathematical operation on Array

In [87]:
# arr = array([10,20,30])
# arr = arr + 5 

In [108]:
from numpy import *

arr = array([10,20,30])

print (arr)

print ('adding 5', arr + 5)

print (arr)

[10 20 30]
adding 5 [15 25 35]
[10 20 30]


In [91]:
print ('substracting 5', arr - 5)

substracting 5 [ 5 15 25]


In [92]:
print ('multiply 5', arr * 5)

multiply 5 [ 50 100 150]


In [93]:
print ("Sin Values", sin(arr))

Sin Values [-0.54402111  0.91294525 -0.98803162]


In [94]:
# Compare arrays

In [98]:
a = array([1,2,3,0])
b = array([0,2,3,2])

c = a == b
print (c) # 1
c = a > b
print (c) # 2
c = a < b
print (c) # 3

[False  True  True False]
[ True False False False]
[False False False  True]


In [100]:
 # any()

a = array([1,2,3,0])
b = array([0,2,3,2])

c = a > b
print (c)

# check if any one element is true

print (any(c))

# check if all elements are true

print (all(c))

if (any(a > b)):
    print ('a contains atleast one element greater than those of b')

[ True False False False]
True
False
a contains atleast one element greater than those of b


In [109]:
# logical operations

from numpy import *

a = array([1,2,3],int)
b = array([0,2,3],int)

c = logical_and(a> 0 , a < 1)
print (c)

c = logical_or(b >= 0 , b ==1)
print (c)

false, true, true > not function > true, false, false
c = logical_not(b)
print (c)

[False False False]
[ True  True  True]
[ True False False]


In [110]:
import numpy as np

In [111]:
help(np.logical_not)

Help on ufunc object:

logical_not = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use np.info().  For
 |  example, np.info(np.sin).  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the "ufuncs.rst"
 |  file in the NumPy reference guide.
 |  
 |  Unary ufuncs:
 |  =============
 |  
 |  op(X, out=None)
 |  Apply op to X elementwise
 |  
 |  Parameters
 |  ----------
 |  X : array_like
 |      Input array.
 |  out : array_like
 |      An array to store the output. Must be the same shape as `X`.
 |  
 |  Returns
 |  -------
 |  r : array_like
 |      `r` will have the same shape as `X`; if out is provided, `r`
 |      will be equal to out.
 |  
 |  Binary ufuncs:
 |  ==============
 |  
 |  op(

In [115]:
# ex very important function of numpy

from numpy import *
a = array([10,20,30,40],int)
b = array([1,21,3,40],int)

# if a > b then take element from a else from b

c = where(a>b,a,b)
print (c)

[10 21 30 40]


In [117]:
# ex very important function of numpy

from numpy import *
a = array([10,20,30,40],int)
b = array([1,21,3,40],int)

# if a > b then take element from a else from b

c = where(a>b,b,a) # inverse
print (c)

[ 1 20  3 40]


In [118]:
# ex 
from numpy import *
a = array([1,2,0,-1,0,6],int)

# retrieve indexes of non zero elements from a
c = nonzero(a)

for i in c:
    print (i)
    
# display the element
print (a[c])

[0 1 3 5]
[ 1  2 -1  6]


In [ ]:
# aliasing the arrays
# a = b # This does not make any new copy of the array 'a'. 
from numpy import *
a = array([1,2,3])

b = a

In [119]:
# ex

from numpy import *

a = arange(1,6)
b = a # shallow copy 

print ('orig array', a)
print ('Alias array', b)


b[0] = 50

print ('After modification')
print ('orig array', a)
print ('Alias array', b)

orig array [1 2 3 4 5]
Alias array [1 2 3 4 5]
After modification
orig array [50  2  3  4  5]
Alias array [50  2  3  4  5]


In [120]:
# ex - copying 

from numpy import *

a = arange(1,6)

b = a.view() # creates a view of a and call it b
# viewing is similar to copying only, it is called as 'shallow copying" . "deep copying"

print ('orig array', a)
print ('View array', b)

b[0] = 50

print ('After modification')
print ('orig array', a)
print ('Alias array', b)

orig array [1 2 3 4 5]
View array [1 2 3 4 5]
After modification
orig array [50  2  3  4  5]
Alias array [50  2  3  4  5]


In [122]:
# ex - copying 

from numpy import *

a = arange(1,6)

b = a.copy() # "deep copying" (copy()), shallow will (view()) effect the orig array. 

print ('orig array', a)
print ('View array', b)

b[0] = 50

print ('After modification')
print ('orig array', a)
print ('New array', b)

orig array [1 2 3 4 5]
View array [1 2 3 4 5]
After modification
orig array [1 2 3 4 5]
New array [50  2  3  4  5]


In [123]:
# Slicing and Indexing in numpy Arrays

In [124]:
from numpy import *

a = arange(10,16)
print (a)

b = a[1:6:2]
print (b)

[10 11 12 13 14 15]
[11 13 15]


In [125]:
# Dimensions of Arrays

In [127]:
# 1 row
arr1 = array([1,2,3,4,5])
print (arr1)

# 1 colum

arr2 = array([10,
             20,
             30,
             40])
print (arr2)


[1 2 3 4 5]
[10 20 30 40]


In [132]:
# 2D
from numpy import *
arr5 = numpy.array([[1,2,3],
            [4,5,6]])
print (arr5)

[[1 2 3]
 [4 5 6]]


In [148]:
# 2D array as a combination of serveral 1D arrays.
from numpy import *
arr5 = numpy.array([[[1,2,3],[1,0,1]],
            [[4,5,6],[1,0,1]]])
print (arr5)
print (arr5.ndim)

[[[1 2 3]
  [1 0 1]]

 [[4 5 6]
  [1 0 1]]]
3


In [139]:
# attributes of an array

In [140]:
# Numpy array class is called as ndarray. ie array. class ndarray or array
# ndim = represents the number of dimensions , ie rank , axes. 

In [141]:
dir()

['ALLOW_THREADS',
 'ArrayType',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'In',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'Out',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_',
 '_6',
 '_8',
 '_95',
 '_96',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__version__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i100',
 '_i101',
 '_i102',
 '_i103',
 '_i104',
 '_i105',
 '_i106',

In [142]:
help(array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [155]:
arr1 = array([1,2,3,4]) # 1D array
print (arr1.ndim)
print (arr1.shape)
print (arr1.size)
print (arr1.itemsize)
print (arr1.dtype)
print (arr1.nbytes)

1
(4,)
4
8
int64
32


In [152]:
arr2 = array([[1,2,3],
              [4,5,6]]) # 2D array
print (arr2.ndim)
print (arr2.shape)
print (arr2.size)

2
(2, 3)
6


In [156]:
# reshape

arr1 = arange(10)
print (arr1)

[0 1 2 3 4 5 6 7 8 9]


In [157]:
arr1 = arr1.reshape(2,5)
print (arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [158]:
arr1 = arr1.reshape(5,2)
print (arr1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [161]:
# flatten()

arr2 = array([[1,2,3],
              [4,5,6]]) # 2D array

print (arr2)

arr2 = arr2.flatten()
print (arr2) # gets converted to 1D

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [162]:
# ex 

a = array([1,2,3,4])
a = array([[1,2,3,4],[1,2,3,4]])

In [163]:
# ones and zeros()

In [165]:
# ones((rows,colums),dtype)

a = ones((3,4),float)
print (a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [167]:
a = zeros((3,4),int)
print (a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [168]:
# eye()

a = eye(3)
print (a)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [169]:
# Indexing in Multi-Dimensional arrays

In [ ]:
a[0][0] # 0th rows and 0th column.
b[1][3] # 1st rows and 3rd column. 

In [172]:
# ex 

a = [[1,2,3],[4,5,6],[7,8,9]]

for i in range(len(a)):
    print ('first', a[i])
    
# display element by element

for i in range(len(a)):
    for j in range(len(a[i])):
        print (a[i][j], end=' ')

first [1, 2, 3]
first [4, 5, 6]
first [7, 8, 9]
1 2 3 4 5 6 7 8 9 

In [ ]:
# Matrix 